server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  mvc:    pathmatch:      matching-strategy: ant-path-matcher

  app:
    login-session-limit-millisecond: 180000

  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_test?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    hikari:      auto-commit: false
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 1200000
      connection-timeout: 20000
      idle-timeout: 300000

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true 
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      
  servlet:
    multipart:
      enabled: true 
      max-file-size: 10MB
      max-request-size: 10MB
      
  devtools:    livereload:      enabled: true
    remote:      restart:        enabled: true

property:
  app:
    static-path: src/main/resources/static/
    temp-upload-path: uploads/tmp
    upload-path-member-pic: uploads/member-profile
    allow-extentions: .png,.jpg,.jpeg,.gif
